name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
          fetch-depth: 1
          path: 1019cc
    - name: test
      run: touch pasttest.txt
    - name: configure
      run: cd ../../
    - name: make test
      run: make test
    - name: make clean
      run: make clean
